spring.application.name=OneToManyMappingSpringBoot

spring.datasource.url=jdbc:mysql://localhost:3306/cea_db?useSSL=false
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Explicitly set Hibernate dialect for MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


UserInterface.NO_CARDS=No associated cards for this customer.
Service.CUSTOMER_NOT_FOUND = Customer details not found.
General.EXCEPTION=Some exception occurred.